### ISSUE TITLE
Project not found

### ISSUE THREAD

**Issue by johanneslagos** [swissknife/circle-monorepo#10]
Hi, I have been testing your orb a little lately. When I follow your example I always got `Project not found `

**Comment by jacktan165** [comment]
You need to set CIRCLE_TOKEN in your environment variables.

**Comment by roopakv** [comment]
Yup @Lilmortal is right. I should make the errors more obvious when CIRCLE_TOKEN isn't set.

Closing this out, please re-open if this does not fix your rpoblem

**Comment by m90** [comment]
I'm somehow seeing this although CIRCLE_TOKEN _is_ set.

**Comment by veriservus** [comment]
@roopakv @m90 -  I've just encountered similar issue [CircleCI explains](https://support.circleci.com/hc/en-us/articles/360060360811-CircleCI-API-v2-returns-404-Not-Found-) that you have to use a personal token as oppose to the project token - changing token type worked for me

**Comment by roopakv** [comment]
Marking this as done. I already updated the documentation to suggest using personal tokens
